# Dependencies
markdown:         kramdown
rouge:         true

# Permalinks
permalink:        pretty

# Setup
title:            Pens and Planes!
tagline:          'Ramblings on pens and planes'
description:      'A Test Site...for now'
url:              www.pensandplanes.org
paginate:         5
baseurl:          ""

author:
  name:           'Jimmy Reekes III'
  url:            https://twitter.com/jmreekes


# Custom vars
version:          1.0.0